//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCNGOAINUOC
    {
        public string TENCHIEU { get; set; }
        public string TEN_NUOC { get; set; }
        public string MASO { get; set; }
        public string CHK { get; set; }
        public short IDC { get; set; }
        public string TENDICHVU { get; set; }
        public int IDDICHVU { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public int IDLYDO { get; set; }
        public string LYDO { get; set; }
        public Nullable<System.DateTime> NGAYHOANTHANH { get; set; }
        public string MA_NUOC { get; set; }
        public Nullable<int> NGUOINHAP { get; set; }
        public string BCNHANKN { get; set; }
    }
}
