//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CONGTHUC_CUOCBT
    {
        public int ID { get; set; }
        public string STTTINH { get; set; }
        public Nullable<int> DICH_VU { get; set; }
        public string TRONG_NUOC { get; set; }
        public Nullable<int> KET_LUAN { get; set; }
        public Nullable<int> LOAI_BT { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string MAB { get; set; }
        public Nullable<int> F { get; set; }
        public string TEN_LYDO_BT { get; set; }
        public string CHK { get; set; }
    }
}
