//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_KHACHHANG
    {
        public int IDKH { get; set; }
        public Nullable<int> DONVI { get; set; }
        public string STTTINH { get; set; }
        public string MAKH { get; set; }
        public string TENTAT { get; set; }
        public string TENKH { get; set; }
        public string NGUOILH { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public string GHICHU { get; set; }
        public string LOAIKH { get; set; }
        public string CHK { get; set; }
    }
}
