//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LYDOKN
    {
        public DM_LYDOKN()
        {
            this.DT_KHIEUNAI = new HashSet<DT_KHIEUNAI>();
        }
    
        public int ID { get; set; }
        public string LYDO { get; set; }
        public string CHK { get; set; }
    
        public virtual ICollection<DT_KHIEUNAI> DT_KHIEUNAI { get; set; }
    }
}
