//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MAU_THONGBAO_BT
    {
        public int MA { get; set; }
        public string STTTINH { get; set; }
        public Nullable<int> LOAI_BT { get; set; }
        public string TRONG_NUOC { get; set; }
        public string TEN_BD1 { get; set; }
        public string TEN_BD2 { get; set; }
        public string TEN_TP { get; set; }
        public string DIEU_1 { get; set; }
        public string DIEU_2 { get; set; }
        public string DIEU_3 { get; set; }
        public string TEN_TT { get; set; }
        public string MAU_BT { get; set; }
    }
}
