//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NUOC
    {
        public DM_NUOC()
        {
            this.DT_KHIEUNAI = new HashSet<DT_KHIEUNAI>();
        }
    
        public string MA_NUOC { get; set; }
        public string TEN_NUOC { get; set; }
        public string MA_VUNG { get; set; }
        public string TEN_VUNG { get; set; }
        public Nullable<int> CACH_TINH_CUOC { get; set; }
        public Nullable<double> TY_LE_CUOC { get; set; }
        public string DON_VI_TIEN_TE { get; set; }
    
        public virtual ICollection<DT_KHIEUNAI> DT_KHIEUNAI { get; set; }
    }
}
