//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_PHONGBAN
    {
        public int MSPB { get; set; }
        public Nullable<int> MSPBCU { get; set; }
        public string BUUDIEN { get; set; }
        public string TENPB { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> STT { get; set; }
        public string CHK { get; set; }
        public string DAUMOI { get; set; }
    }
}
