//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TINH_TP
    {
        public DM_TINH_TP()
        {
            this.DT_KHIEUNAI = new HashSet<DT_KHIEUNAI>();
        }
    
        public int ID_Tinh_TP { get; set; }
        public Nullable<decimal> STT_Tinh_TP { get; set; }
        public string Ten_Tinh_TP { get; set; }
        public string TEN_BD { get; set; }
        public string IP_Tinh_TP { get; set; }
        public string Ma_vung_BK { get; set; }
        public string Ma_Vung_EMS { get; set; }
        public Nullable<decimal> MA_TT_KT { get; set; }
        public string NHOM_TINH { get; set; }
    
        public virtual ICollection<DT_KHIEUNAI> DT_KHIEUNAI { get; set; }
    }
}
