//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_KHIEUNAI_CHUYENTHU
    {
        public decimal IDCTKN { get; set; }
        public string IDKHIEUNAI { get; set; }
        public string BCGOC { get; set; }
        public string BCNHAN { get; set; }
        public Nullable<int> SOCT { get; set; }
        public Nullable<System.DateTime> NGAYDONG { get; set; }
        public Nullable<int> SOTUI { get; set; }
        public Nullable<int> PHUONGTHUC { get; set; }
        public Nullable<int> DONG { get; set; }
        public string GHICHU { get; set; }
        public string NGUOINHAP { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public string CHK { get; set; }
        public string XOA { get; set; }
        public string DATRUYEN { get; set; }
    }
}
