//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_KHIEUNAI_TIENTRINH
    {
        public decimal IDCTKN { get; set; }
        public string IDKHIEUNAI { get; set; }
        public string NOIDUNG { get; set; }
        public string NOIDUNGTA { get; set; }
        public string NOIDUNGBC08 { get; set; }
        public Nullable<System.DateTime> NGAYCHUYEN { get; set; }
        public Nullable<System.DateTime> NGAYPHAT { get; set; }
        public string FILEDK { get; set; }
        public Nullable<int> KETQUA { get; set; }
        public string NGUOINHAP { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public string XULY { get; set; }
        public string CHK { get; set; }
        public string NGUOIXLYTIEP { get; set; }
        public string DATRUYEN { get; set; }
    }
}
