//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_KHIEUNAI_BOITHUONG
    {
        public int IDBT { get; set; }
        public string IDKHIEUNAI { get; set; }
        public string NGUOIBT { get; set; }
        public string TRANGTHAI { get; set; }
        public string NGUOINHAP { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public Nullable<int> LOAI_BT { get; set; }
        public Nullable<int> TIENHOANCUOC { get; set; }
        public Nullable<int> TIENBT { get; set; }
        public string BAOHIEM { get; set; }
        public string SOQDBOITHUONG { get; set; }
        public string SOTBBOITHUONG { get; set; }
        public Nullable<System.DateTime> NGAYKYBT { get; set; }
        public string FILEQDBT { get; set; }
        public string DA_CHI_BT { get; set; }
        public string SOQDTHUHOI { get; set; }
        public string SOTBTHUHOI { get; set; }
        public string FILEQDTH { get; set; }
        public Nullable<System.DateTime> NGAYTHUHOI { get; set; }
        public string CHK { get; set; }
        public string NGUOI_CHI_TIEN { get; set; }
    }
}
