//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_KHIEUNAI_TAM
    {
        public decimal MS_KHIEUNAI { get; set; }
        public string STTTINH { get; set; }
        public Nullable<byte> CHIEU { get; set; }
        public Nullable<short> IDPTTL { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public Nullable<System.DateTime> HETHAN { get; set; }
        public Nullable<int> LOAIDV { get; set; }
        public Nullable<int> DICHVU { get; set; }
        public string DICHVUDB { get; set; }
        public string SOHIEUBG { get; set; }
        public Nullable<int> LYDOKN { get; set; }
        public Nullable<byte> MUCDO { get; set; }
        public string FILEDK { get; set; }
        public string GHICHU { get; set; }
        public string NGUOIGOI { get; set; }
        public string DCGOI { get; set; }
        public Nullable<int> TINHGOI { get; set; }
        public string NUOCGOI { get; set; }
        public string NGUOINHAN { get; set; }
        public string DCNHAN { get; set; }
        public Nullable<int> TINHNHAN { get; set; }
        public string NUOCNHAN { get; set; }
        public string BCGOI { get; set; }
        public string BCNHANKN { get; set; }
        public Nullable<System.DateTime> NGAYGOI { get; set; }
        public Nullable<float> KHOILUONG { get; set; }
        public Nullable<byte> PLNOIDUNG { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<byte> TRONGNUOC { get; set; }
        public string NGUOIKN { get; set; }
        public string DIACHI { get; set; }
        public string DTFAX { get; set; }
        public string EMAIL { get; set; }
        public string NGUOINHAP { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public string PHONGBAN { get; set; }
        public Nullable<short> LANKN { get; set; }
        public string CHK { get; set; }
        public string HUYKN { get; set; }
        public Nullable<int> NGUOIHUY { get; set; }
        public Nullable<System.DateTime> NGAYHUY { get; set; }
        public Nullable<int> CUOC { get; set; }
        public Nullable<int> THOIGIAN { get; set; }
        public Nullable<System.DateTime> NGAYHH { get; set; }
        public string KNDACBIET { get; set; }
        public Nullable<System.DateTime> NGAYHOANTHANH { get; set; }
        public Nullable<int> NGUYENNHAN { get; set; }
        public string KHLON { get; set; }
        public Nullable<short> HTVCHUYEN { get; set; }
        public Nullable<System.DateTime> NGAY_CT { get; set; }
        public Nullable<int> SOTUI { get; set; }
        public Nullable<int> SOCHUYEN { get; set; }
        public string BCGUI_BG { get; set; }
        public string BCNHAN_BG { get; set; }
        public string DATRUYEN { get; set; }
        public string ISKHL { get; set; }
    }
}
