//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_KHIEUNAI_USER
    {
        public decimal ID { get; set; }
        public string IDKHIEUNAI { get; set; }
        public string USERNAME { get; set; }
        public string PHONGBAN { get; set; }
        public string CHK { get; set; }
        public string USERTAO { get; set; }
        public string DATRUYEN { get; set; }
    
        public virtual DT_KHIEUNAI DT_KHIEUNAI { get; set; }
    }
}
