//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_NGAY
    {
        public int IDNGAY { get; set; }
        public string TENNGAY { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<short> THANG { get; set; }
        public Nullable<short> NAM { get; set; }
    }
}
