//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USER
    {
        public int USERID { get; set; }
        public Nullable<short> STTTINH { get; set; }
        public string USERNAME { get; set; }
        public string MATKHAU { get; set; }
        public string TENNV { get; set; }
        public string SODT { get; set; }
        public string DIACHI { get; set; }
        public string PHONGBAN { get; set; }
        public string SHBUUCUC { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string NGUOINHAP { get; set; }
        public string CHK { get; set; }
        public string CHUCVU { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public string CMND { get; set; }
        public string SHINNHATAN { get; set; }
        public Nullable<short> DAUMOI { get; set; }
        public Nullable<short> DAUMOINB { get; set; }
    }
}
