//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW1
    {
        public string MS_KHIEUNAI { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public string SOHIEUBG { get; set; }
        public string LYDO { get; set; }
        public string TENCHIEU { get; set; }
        public string FILEDK { get; set; }
        public string TENNV { get; set; }
        public string TENDICHVU { get; set; }
        public Nullable<byte> MUCDO { get; set; }
        public string GHICHU { get; set; }
        public string NGUOIGOI { get; set; }
        public string DCGOI { get; set; }
        public string NGUOINHAN { get; set; }
        public string DCNHAN { get; set; }
        public string BCGOI { get; set; }
        public string BCNHAN { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<System.DateTime> NGAYGOI { get; set; }
        public Nullable<float> KHOILUONG { get; set; }
        public Nullable<byte> TRONGNUOC { get; set; }
        public string NGUOIKN { get; set; }
        public string DIACHI { get; set; }
        public string DTFAX { get; set; }
        public string EMAIL { get; set; }
        public Nullable<short> LANKN { get; set; }
        public string TINHNHAN { get; set; }
        public string NUOCNHAN { get; set; }
        public string TINHGOI { get; set; }
        public string NUOCGOI { get; set; }
        public string TENLH { get; set; }
        public string CHK { get; set; }
    }
}
