using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Models.AddMailTrip
{
    public class ListItemDTO
    {
        public string ItemCode { get; set; }
        public string AcceptancePOSCode { get; set; }
        public string SenderFullname { get; set; }
        public string SenderAddress { get; set; }
        public string CustomerCode { get; set; }
        public string BatchCode { get; set; }
        public string ReceiverFullname { get; set; }
        public string ReceiverTel { get; set; }
        public string ReceiverAddress { get; set; }
        public int isDomestic { get; set; }
        public string CountryCode { get; set; }
        public int POSCode { get; set; }
        public int IsStatePrice { get; set; }
        public int StatePriceValue { get; set; }
        public int SendingContent { get; set; }
        public int Note { get; set; }
        public string ItemTypeCode { get; set; }
        public int SendingTime { get; set; }
        public int IsAirmail { get; set; }
        public int Weight { get; set; }
        public int Status { get; set; }
        public int TotalFreight { get; set; }
        public int EmployeeCode { get; set; }
        public string SenderJob { get; set; }
        public string ProvinceCode { get; set; }
        public int LightItem { get; set; }
        public string SectionCode { get; set; }
        public string ReceiverJob { get; set; }
        public int IsOpened { get; set; }
        public string CertificateNumber { get; set; }
        public string LicenseNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public string SenderIdentification { get; set; }
        public Nullable<int> SenderIssueDate { get; set; }
        public string SenderIssueCountry { get; set; }
        public string ReceiverIdentification { get; set; }
        public Nullable<int> ReceiverIssueDate { get; set; }
        public string ReceiverIssueCountry { get; set; }
        public string SenderTel { get; set; }
        public int MainFreight { get; set; }
        public decimal VATFreight { get; set; }
        public int SubFreight { get; set; }
        public int IsPostFree { get; set; }
        public int StatePriceFreight { get; set; }
        public int PrintedNumber { get; set; }
        public string DataCode { get; set; }
        public string SenderCustomReference { get; set; }
        public int RemainingFreight { get; set; }
        public string ReceiverCustomReference { get; set; }
        public int IsReturn { get; set; }
        public int IsCompensate { get; set; }
        public int IsForward { get; set; }
        public int IsAirmailForward { get; set; }
        public int IsAirmailReturn { get; set; }
        public int IsDebt { get; set; }
        public string MachineName { get; set; }
        public int AcceptedIndex { get; set; }
        public int BC16Index { get; set; }
        public int IncomingIndex { get; set; }
        public string ServiceCode { get; set; }
        public string ReceiverDistrictCode { get; set; }
        public int LetterMoneyOrderFreight { get; set; }
        public int VASFTF { get; set; }
        public string OrderCode { get; set; }
        public string ReceiverAddressCode { get; set; }
        public string SenderMobile { get; set; }
        public string SenderFax { get; set; }
        public string SenderEmail { get; set; }
        public string ReceiverMobile { get; set; }
        public string ReceiverFax { get; set; }
        public string ReceiverEmail { get; set; }
        public int Discount { get; set; }
        public int Abatement { get; set; }
        public int UndeliverableGuide { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int Length { get; set; }
        public string CheckSum { get; set; }
        public string ItemNumber { get; set; }
        public string ExchangeRateCode { get; set; }
        public string CODAddress { get; set; }
        public int CODPayment { get; set; }
        public string SenderDistrictCode { get; set; }
        public string ReceiverContact { get; set; }
        public int UndeliverableReason { get; set; }
        public int DecisionNo { get; set; }
        public Nullable<int> DecisionDate { get; set; }
        public int ReturnDayNumber { get; set; }
        public int DiscountPercentage { get; set; }
        public int DiscountAmount { get; set; }
        public int ExecuteOrder { get; set; }
        public int InvoiceAttached { get; set; }
        public int OtherAttached { get; set; }
        public int OtherAttachedInfor { get; set; }
        public int TransferMachine { get; set; }
        public int TransferUser { get; set; }
        public int TransferPOSCode { get; set; }
        public int TransferDate { get; set; }
        public int TransferStatus { get; set; }
        public int TransferTimes { get; set; }
        public int WeightConvert { get; set; }
        public int IsDiscount { get; set; }
        public int InvoiceExport { get; set; }
        public int Total { get; set; }
        public int AcceptedType { get; set; }
        public int SenderTaxCode { get; set; }
        public int VATPercentage { get; set; }
        public int FuelSurchargeFreight { get; set; }
        public int FarRegionFreight { get; set; }
        public int AirSurchargeFreight { get; set; }
        public int OtherFreight { get; set; }
        public decimal TotalFreightVAT { get; set; }
        public int TotalFreightDiscount { get; set; }
        public decimal TotalFreightDiscountVAT { get; set; }
        public string ReceiverTaxCode { get; set; }
        public int FarRegion { get; set; }
        public int IsCollection { get; set; }
        public string CustomerAccountNo { get; set; }
        public int IsFeedback { get; set; }
        public int FeedbackPercentage { get; set; }
        public int FeedbackAmount { get; set; }
        public int PaymentFreight { get; set; }
        public decimal PaymentFreightVAT { get; set; }
        public int PaymentFreightDiscount { get; set; }
        public int PaymentFreightDiscountVAT { get; set; }
        public int RemainingFreightVAT { get; set; }
        public int RemainingFreightDiscount { get; set; }
        public int RemainingFreightDiscountVAT { get; set; }
        public int DeliveryCounter { get; set; }
        public string AdviceOfReceiptCode { get; set; }
        public string ReceiverCommuneCode { get; set; }
        public string CheckContentOnDeliveryCode { get; set; }
        public string DestinationPOSCode { get; set; }
        public int IsAffair { get; set; }
        public Nullable<int> ReturnBeforeDate { get; set; }
        public string CustomerGroupCode { get; set; }
        public int OrtherFreight { get; set; }
        public int OriginalMainFreight { get; set; }
        public int OriginalSubFreight { get; set; }
        public int OriginalFuelSurchargeFreight { get; set; }
        public int OriginalFarRegionFreight { get; set; }
        public int OriginalAirSurchargeFreight { get; set; }
        public int OriginalVATFreight { get; set; }
        public int OriginalVATPercentage { get; set; }
        public int OriginalTotalFreight { get; set; }
        public int OriginalTotalFreightVAT { get; set; }
        public int OriginalTotalFreightDiscount { get; set; }
        public int OTFDVAT { get; set; }
        public int OriginalPaymentFreight { get; set; }
        public int OriginalPaymentFreightVAT { get; set; }
        public int OriginalPaymentFreightDiscount { get; set; }
        public int OPFDVAT { get; set; }
        public int OriginalRemainingFreight { get; set; }
        public int OriginalRemainingFreightVAT { get; set; }
        public int ORFDiscount { get; set; }
        public int ORFDVAT { get; set; }
        public int IsEcommerce { get; set; }
        // traceItem
        public int TraceIndex1 { get; set; }
        public string ItemCode1 { get; set; }
        public int POSCode1 { get; set; }
        public int Status1 { get; set; }
        public DateTime TraceDate1 { get; set; }
        public string StatusDesc1 { get; set; }
        public string Note1 { get; set; }
        public string TransferMachine1 { get; set; }
        public string TransferUser1 { get; set; }
        public string TransferPOSCode1 { get; set; }
        public Nullable<int> TransferDate1 { get; set; }
        public int TransferStatus1 { get; set; }
        public int TransferTimes1 { get; set; }
        public string ServiceCode2 { get; set; }
        public string ItemCode2 { get; set; }
        public int Freight2 { get; set; }
        public string PhaseCode2 { get; set; }
        public DateTime AddedDate2 { get; set; }
        public decimal FreightVAT2 { get; set; }
        public int POSCode2 { get; set; }
        public int OriginalFreight2 { get; set; }
        public decimal OriginalFreightVAT2 { get; set; }
        //ItemVASPropertyValue
        public string ItemCode3 { get; set; }
        public int PropertyCode { get; set; }
    }
}
